param(
    [string]$NodeRedUrl = "http://127.0.0.1:1880",
    [string]$NodeRedUserDir = "C:\Users\asus\.node-red",
    [string]$GatewayStatusUrl = "http://192.168.4.1/api/status",
    [string]$GatewayBaseUrl = "http://192.168.4.1",
    [string]$MqttHost = "CHANGE_ME_MQTT_HOST",
    [int]$MqttPort = 1883,
    [string]$MqttUser = $env:MQTT_USER,
    [string]$MqttPassword = $env:MQTT_PASS,
    [switch]$GenerateOnly
)

$ErrorActionPreference = "Stop"
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$decodeFunctionPath = Join-Path $scriptDir "functions\pertamina-gld-decode.js"
$decodeFunction = Get-Content -Path $decodeFunctionPath -Raw

function New-NodeId($name) {
    return "pgl_" + $name
}

$tab = New-NodeId "tab"
$broker = New-NodeId "mqtt_broker"

$nodes = @(
    @{
        id = $tab; type = "tab"; label = "Pertamina GLD Server"; disabled = $false
        info = "Generated by D:\PertaminaGLD\server\nodered\apply-pertamina-gld-flow.ps1"
        env = @(
            @{ name = "GATEWAY_STATUS_URL"; value = $GatewayStatusUrl; type = "str" },
            @{ name = "GATEWAY_BASE_URL"; value = $GatewayBaseUrl; type = "str" },
            @{ name = "PGL_GATEWAY_ID"; value = "0x006F"; type = "str" }
        )
    },
    @{
        id = New-NodeId "poll_gateway"; type = "inject"; z = $tab; name = "poll Gateway /api/status"
        props = @(@{ p = "payload" }, @{ p = "topic"; vt = "str" })
        repeat = "5"; crontab = ""; once = $true; onceDelay = "2"; topic = "gateway/status/poll"; payload = ""; payloadType = "date"
        x = 180; y = 100; wires = @(@((New-NodeId "http_gateway_status")))
    },
    @{
        id = New-NodeId "http_gateway_status"; type = "http request"; z = $tab; name = "GET Gateway status"
        method = "GET"; ret = "obj"; paytoqs = "ignore"; url = $GatewayStatusUrl; tls = ""; persist = $false; proxy = ""; insecureHTTPParser = $false; authType = ""
        x = 420; y = 100; wires = @(@((New-NodeId "decode")))
    },
    @{
        id = New-NodeId "test_vector"; type = "inject"; z = $tab; name = "GLD AES-GCM test vector"
        props = @(@{ p = "payload" }, @{ p = "topic"; vt = "str" })
        repeat = ""; crontab = ""; once = $false; onceDelay = "0.1"; topic = "gld/test/vector"
        payload = '{"recordHex":"F0012A111D01101112131415161718191A1BC57E0DDBF88ABEC591E9F5BFAD982A6C"}'
        payloadType = "json"; x = 190; y = 180; wires = @(@((New-NodeId "decode")))
    },
    @{
        id = New-NodeId "decode"; type = "function"; z = $tab; name = "decode Gateway/GLD contract"
        func = $decodeFunction; outputs = 4; timeout = 0; noerr = 0; initialize = ""; finalize = ""
        libs = @(@{ var = "crypto"; module = "crypto" })
        x = 700; y = 140
        wires = @(
            @((New-NodeId "mqtt_status"), (New-NodeId "debug_status")),
            @((New-NodeId "mqtt_events"), (New-NodeId "debug_events")),
            @((New-NodeId "mqtt_decoded"), (New-NodeId "compact_decoded_debug")),
            @((New-NodeId "mqtt_error"), (New-NodeId "debug_error"))
        )
    },
    @{
        id = New-NodeId "mqtt_status"; type = "mqtt out"; z = $tab; name = "MQTT gateway status"; topic = "gld/gateway/status"; qos = "0"; retain = ""; respTopic = ""; contentType = "application/json"; userProps = ""; correl = ""; expiry = ""; broker = $broker
        x = 990; y = 80; wires = @()
    },
    @{
        id = New-NodeId "mqtt_events"; type = "mqtt out"; z = $tab; name = "MQTT gateway events"; topic = "gld/gateway/events"; qos = "0"; retain = ""; respTopic = ""; contentType = "application/json"; userProps = ""; correl = ""; expiry = ""; broker = $broker
        x = 990; y = 120; wires = @()
    },
    @{
        id = New-NodeId "mqtt_decoded"; type = "mqtt out"; z = $tab; name = "MQTT decoded/alarm"; topic = ""; qos = "0"; retain = ""; respTopic = ""; contentType = "application/json"; userProps = ""; correl = ""; expiry = ""; broker = $broker
        x = 990; y = 160; wires = @()
    },
    @{
        id = New-NodeId "compact_decoded_debug"; type = "function"; z = $tab; name = "compact decoded debug"
        func = "const p = msg.payload || {};`nconst outer = p.outer || {};`nconst response = outer.response || {};`nmsg.payload = {`n  nodeIdHex: p.nodeIdHex,`n  seq: p.seq,`n  requestId: response.requestId,`n  responseFromCh: {`n    msgType: outer.msgType !== undefined ? `"0x`" + Number(outer.msgType).toString(16).toUpperCase().padStart(2, `"0`") : undefined,`n    from: outer.srcIdHex,`n    to: outer.dstIdHex,`n    seq: outer.seq,`n    requestId: response.requestId,`n    status: response.status,`n    chBatteryMv: response.chBatteryMv,`n    recordCount: response.recordCount,`n    payloadLen: outer.payloadLen,`n    payloadHex: outer.payloadHex`n  },`n  gasName: p.gasName,`n  gasClass: p.gasClass,`n  confidence: p.confidence,`n  alarm: p.alarm,`n  externalPower: p.externalPower,`n  batteryMv: p.batteryMv,`n  decryptOk: p.decryptOk,`n  route: outer.srcIdHex && outer.dstIdHex ? outer.srcIdHex + `" -> `" + outer.dstIdHex : undefined`n};`nreturn msg;"
        outputs = 1; timeout = 0; noerr = 0; initialize = ""; finalize = ""; libs = @()
        x = 990; y = 340; wires = @(@((New-NodeId "debug_decoded")))
    },
    @{
        id = New-NodeId "mqtt_error"; type = "mqtt out"; z = $tab; name = "MQTT errors"; topic = "gld/gateway/error"; qos = "0"; retain = ""; respTopic = ""; contentType = "application/json"; userProps = ""; correl = ""; expiry = ""; broker = $broker
        x = 990; y = 200; wires = @()
    },
    @{
        id = New-NodeId "debug_status"; type = "debug"; z = $tab; name = "[STATUS] gateway alive"; active = $false; tosidebar = $true; console = $false; tostatus = $true; complete = "payload"; targetType = "msg"; statusVal = "payload.kind"; statusType = "msg"
        x = 970; y = 260; wires = @()
    },
    @{
        id = New-NodeId "debug_events"; type = "debug"; z = $tab; name = "[EVENT] gateway envelope"; active = $false; tosidebar = $true; console = $false; tostatus = $true; complete = "payload"; targetType = "msg"; statusVal = "payload.kind"; statusType = "msg"
        x = 970; y = 300; wires = @()
    },
    @{
        id = New-NodeId "debug_decoded"; type = "debug"; z = $tab; name = "[DECODED FINAL] GLD server data"; active = $true; tosidebar = $true; console = $false; tostatus = $true; complete = "payload"; targetType = "msg"; statusVal = "payload.gasName"; statusType = "msg"
        x = 1240; y = 340; wires = @()
    },
    @{
        id = New-NodeId "debug_error"; type = "debug"; z = $tab; name = "[ERROR] decode/server"; active = $true; tosidebar = $true; console = $false; tostatus = $true; complete = "payload"; targetType = "msg"; statusVal = "payload.reason"; statusType = "msg"
        x = 970; y = 380; wires = @()
    },
    @{
        id = New-NodeId "mqtt_cmd_pull"; type = "mqtt in"; z = $tab; name = "cmd pull"; topic = "gld/gateway/cmd/pull"; qos = "0"; datatype = "json"; broker = $broker; nl = $false; rap = $true; rh = 0; inputs = 0
        x = 170; y = 500; wires = @(@((New-NodeId "build_pull")))
    },
    @{
        id = New-NodeId "build_pull"; type = "function"; z = $tab; name = "build /api/pull POST"
        func = "const base = env.get('GATEWAY_BASE_URL') || '$GatewayBaseUrl';\nconst p = msg.payload || {};\nconst hopList = Array.isArray(p.hopList) ? p.hopList : (Array.isArray(p.hop_list) ? p.hop_list : [p.cluster || p.clusterId || '0x0064']);\nconst cluster = hopList[0] || '0x0064';\nmsg.method = 'POST';\nmsg.url = `${base}/api/pull?cluster=${encodeURIComponent(cluster)}`;\nmsg.payload = '';\nreturn msg;"
        outputs = 1; timeout = 0; noerr = 0; initialize = ""; finalize = ""; libs = @()
        x = 420; y = 500; wires = @(@((New-NodeId "http_command"), (New-NodeId "debug_command")))
    },
    @{
        id = New-NodeId "mqtt_cmd_node"; type = "mqtt in"; z = $tab; name = "cmd node"; topic = "gld/gateway/cmd/node"; qos = "0"; datatype = "json"; broker = $broker; nl = $false; rap = $true; rh = 0; inputs = 0
        x = 170; y = 560; wires = @(@((New-NodeId "build_node_command")))
    },
    @{
        id = New-NodeId "build_node_command"; type = "function"; z = $tab; name = "build /api/command POST"
        func = "const base = env.get('GATEWAY_BASE_URL') || '$GatewayBaseUrl';\nconst p = msg.payload || {};\nconst cluster = p.cluster || p.clusterId || '0x0064';\nconst node = p.node || p.nodeId || '0xF001';\nconst id = p.id || p.commandId || 1;\nconst ttl = p.ttl || p.ttlSec || 600;\nconst hex = p.hex || '';\nmsg.method = 'POST';\nmsg.url = `${base}/api/command?cluster=${encodeURIComponent(cluster)}&node=${encodeURIComponent(node)}&id=${encodeURIComponent(id)}&ttl=${encodeURIComponent(ttl)}&hex=${encodeURIComponent(hex)}`;\nmsg.payload = '';\nreturn msg;"
        outputs = 1; timeout = 0; noerr = 0; initialize = ""; finalize = ""; libs = @()
        x = 430; y = 560; wires = @(@((New-NodeId "http_command"), (New-NodeId "debug_command")))
    },
    @{
        id = New-NodeId "http_command"; type = "http request"; z = $tab; name = "POST Gateway command"; method = "use"; ret = "obj"; paytoqs = "ignore"; url = ""; tls = ""; persist = $false; proxy = ""; insecureHTTPParser = $false; authType = ""
        x = 720; y = 530; wires = @(@((New-NodeId "debug_command_response")))
    },
    @{
        id = New-NodeId "debug_command"; type = "debug"; z = $tab; name = "[CMD] HTTP bridge request"; active = $false; tosidebar = $true; console = $false; tostatus = $true; complete = "url"; targetType = "msg"; statusVal = "url"; statusType = "msg"
        x = 720; y = 610; wires = @()
    },
    @{
        id = New-NodeId "debug_command_response"; type = "debug"; z = $tab; name = "[CMD] HTTP bridge response"; active = $false; tosidebar = $true; console = $false; tostatus = $true; complete = "payload"; targetType = "msg"; statusVal = "statusCode"; statusType = "msg"
        x = 990; y = 530; wires = @()
    },
    @{
        id = $broker; type = "mqtt-broker"; name = "Pertamina GLD MQTT"; broker = $MqttHost; port = [string]$MqttPort; clientid = "node-red-pertamina-gld"; autoConnect = $true; usetls = $false; protocolVersion = "4"; keepalive = "60"; cleansession = $true; birthTopic = ""; birthQos = "0"; birthPayload = ""; birthMsg = @{}; closeTopic = ""; closeQos = "0"; closePayload = ""; closeMsg = @{}; willTopic = ""; willQos = "0"; willPayload = ""; willMsg = @{}; userProps = ""; sessionExpiry = ""
    }
)

$generatedPath = Join-Path $scriptDir "pertamina-gld-server.flow.json"
$nodes | ConvertTo-Json -Depth 30 | Set-Content -Path $generatedPath -Encoding UTF8

if ($GenerateOnly) {
    [pscustomobject]@{
        Generated = $true
        FlowFile = $generatedPath
        Nodes = $nodes.Count
    } | ConvertTo-Json -Compress
    exit 0
}

$timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
$backupDir = Join-Path $NodeRedUserDir "pertamina-gld-backups"
New-Item -ItemType Directory -Force -Path $backupDir | Out-Null
Copy-Item -Path (Join-Path $NodeRedUserDir "flows.json") -Destination (Join-Path $backupDir "flows.$timestamp.json") -Force
if (Test-Path (Join-Path $NodeRedUserDir "flows_cred.json")) {
    Copy-Item -Path (Join-Path $NodeRedUserDir "flows_cred.json") -Destination (Join-Path $backupDir "flows_cred.$timestamp.json") -Force
}
foreach ($optionalFile in @("settings.js", "package.json", "package-lock.json", ".config.runtime.json")) {
    $source = Join-Path $NodeRedUserDir $optionalFile
    if (Test-Path $source) {
        Copy-Item -Path $source -Destination (Join-Path $backupDir "$optionalFile.$timestamp.bak") -Force
    }
}

$flowsEndpoint = "$NodeRedUrl/flows"
$current = Invoke-RestMethod -Uri $flowsEndpoint -Method Get -TimeoutSec 10
$apiUsesEnvelope = $false
$existingFlows = @()
if ($current.PSObject.Properties.Name -contains "flows") {
    $apiUsesEnvelope = $true
    $existingFlows = @($current.flows)
} elseif ($current.PSObject.Properties.Name -contains "value") {
    $existingFlows = @($current.value)
} else {
    $existingFlows = @($current)
}

$kept = @($existingFlows | Where-Object {
    $id = [string]$_.id
    -not ($id.StartsWith("pgl_") -or $id -eq $broker)
})
$merged = @($kept + $nodes)

$headers = @{
    "Node-RED-Deployment-Type" = "full"
}

if ($apiUsesEnvelope) {
    $body = @{
        rev = $current.rev
        flows = $merged
        credentials = @{}
    }

    if ($MqttUser -and $MqttPassword) {
        $body.credentials[$broker] = @{
            user = $MqttUser
            password = $MqttPassword
        }
    }
} else {
    $body = $merged
}

$json = $body | ConvertTo-Json -Depth 50
$response = Invoke-RestMethod -Uri $flowsEndpoint -Method Post -Headers $headers -ContentType "application/json" -Body $json -TimeoutSec 60

[pscustomobject]@{
    Applied = $true
    NodeRedUrl = $NodeRedUrl
    FlowFile = $generatedPath
    BackupDir = $backupDir
    AddedNodes = $nodes.Count
    TotalNodes = $merged.Count
    ApiUsesEnvelope = $apiUsesEnvelope
    ResponseRev = $response.rev
} | ConvertTo-Json -Compress
